--!strict
--[[ Enemy catalog — 30+ unique behaviors. Cartoon violence. Turtles always allies. ]]

local Enemies = {}

export type EnemyDef = {
	id: string,
	name: string,
	hp: number,
	damage: number,
	speed: number,
	color: Color3,
	accent: Color3,
	size: Vector3,
	telegraph: number,
	attackCooldown: number,
	isBoss: boolean,
	isMiniboss: boolean,
	isAlly: boolean,
	dropsPersona: string?,
	dropsItem: string?,
	flavor: string,
	shape: string,
	behavior: string,
}

local list: { EnemyDef } = {
	{ id = "BeachCrab", name = "Beach Crab", hp = 28, damage = 6, speed = 10,
		color = Color3.fromRGB(220, 70, 50), accent = Color3.fromRGB(255, 180, 100),
		size = Vector3.new(3.2, 1.6, 3.2), telegraph = 0.45, attackCooldown = 1.4,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = nil,
		flavor = "Stole your Cold One.", shape = "crab", behavior = "scuttle" },
	{ id = "HermitCrab", name = "Hermit Crab", hp = 36, damage = 7, speed = 7,
		color = Color3.fromRGB(180, 90, 60), accent = Color3.fromRGB(120, 80, 50),
		size = Vector3.new(2.8, 2.2, 2.8), telegraph = 0.5, attackCooldown = 1.6,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "SeashellShield",
		flavor = "Shell tank. Slow pinch.", shape = "crab", behavior = "tank" },
	{ id = "SandFlea", name = "Sand Flea", hp = 18, damage = 5, speed = 16,
		color = Color3.fromRGB(200, 180, 120), accent = Color3.fromRGB(255, 220, 160),
		size = Vector3.new(1.6, 1.2, 1.6), telegraph = 0.25, attackCooldown = 1.0,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = nil,
		flavor = "Annoying hoppers.", shape = "hopper", behavior = "hopper" },
	{ id = "AngryTourist", name = "Angry Tourist", hp = 40, damage = 8, speed = 9,
		color = Color3.fromRGB(255, 210, 160), accent = Color3.fromRGB(80, 140, 200),
		size = Vector3.new(2.4, 5, 2), telegraph = 0.5, attackCooldown = 1.6,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "IHeartFLShirt",
		flavor = "Lost. Taking it personally.", shape = "humanoid", behavior = "chase" },
	{ id = "SelfieZombie", name = "Selfie Tourist", hp = 34, damage = 6, speed = 8,
		color = Color3.fromRGB(255, 200, 180), accent = Color3.fromRGB(100, 200, 255),
		size = Vector3.new(2.2, 4.8, 2), telegraph = 0.7, attackCooldown = 2.0,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "CrackedVisor",
		flavor = "Flashes then shoves.", shape = "humanoid", behavior = "spitter" },
	{ id = "SlushieSlime", name = "Slushie Slime", hp = 34, damage = 7, speed = 7,
		color = Color3.fromRGB(255, 60, 160), accent = Color3.fromRGB(120, 255, 255),
		size = Vector3.new(3.5, 2.5, 3.5), telegraph = 0.55, attackCooldown = 1.8,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "GasStationTaquito",
		flavor = "Floor is sticky.", shape = "slime", behavior = "puddle" },
	{ id = "HotDogCart", name = "Runaway Hotdog Cart", hp = 50, damage = 10, speed = 14,
		color = Color3.fromRGB(220, 40, 40), accent = Color3.fromRGB(255, 220, 80),
		size = Vector3.new(4, 3, 2.5), telegraph = 0.4, attackCooldown = 2.2,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "NoveltyMug",
		flavor = "Charger with mustard trail.", shape = "cart", behavior = "charger" },
	{ id = "DriveThruGator", name = "Drive-Thru Gator", hp = 160, damage = 14, speed = 8,
		color = Color3.fromRGB(45, 110, 55), accent = Color3.fromRGB(180, 160, 40),
		size = Vector3.new(7, 3.2, 3.5), telegraph = 0.7, attackCooldown = 2.0,
		isBoss = false, isMiniboss = true, isAlly = false, dropsPersona = "GatorHauler", dropsItem = "RadioCollar",
		flavor = "Radio collar beeping.", shape = "gator", behavior = "tank" },
	{ id = "Cottonmouth", name = "Cottonmouth", hp = 32, damage = 9, speed = 14,
		color = Color3.fromRGB(60, 80, 50), accent = Color3.fromRGB(240, 240, 220),
		size = Vector3.new(4, 1.2, 1.2), telegraph = 0.35, attackCooldown = 1.2,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = "SnakeCharmer", dropsItem = nil,
		flavor = "Hisses in lowercase.", shape = "snake", behavior = "chase" },
	{ id = "BurrowSnake", name = "Burrow Snake", hp = 38, damage = 10, speed = 11,
		color = Color3.fromRGB(80, 60, 40), accent = Color3.fromRGB(200, 180, 120),
		size = Vector3.new(3.5, 1.0, 1.0), telegraph = 0.55, attackCooldown = 1.8,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "LiveBait",
		flavor = "Pops from sand.", shape = "snake", behavior = "burrower" },
	{ id = "OilGator", name = "Oil Gator", hp = 70, damage = 12, speed = 8,
		color = Color3.fromRGB(25, 35, 30), accent = Color3.fromRGB(40, 80, 30),
		size = Vector3.new(6, 2.8, 3), telegraph = 0.65, attackCooldown = 1.7,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "SpillAbsorbent",
		flavor = "Sludge armor. GulfGulp property.", shape = "gator", behavior = "puddle" },
	{ id = "FireLizard", name = "Fire Lizard", hp = 48, damage = 11, speed = 12,
		color = Color3.fromRGB(255, 90, 20), accent = Color3.fromRGB(255, 220, 60),
		size = Vector3.new(3.5, 2.2, 4), telegraph = 0.5, attackCooldown = 1.5,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = "LizardBreath", dropsItem = nil,
		flavor = "Cartoon fire breath.", shape = "lizard", behavior = "firearc" },
	{ id = "EmberSkink", name = "Ember Skink", hp = 28, damage = 8, speed = 15,
		color = Color3.fromRGB(255, 140, 40), accent = Color3.fromRGB(255, 80, 20),
		size = Vector3.new(2.2, 1.4, 3), telegraph = 0.35, attackCooldown = 1.2,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "ExpiredSunscreen",
		flavor = "Tiny flame arcs.", shape = "lizard", behavior = "firearc" },
	{ id = "GulfGulpGrunt", name = "GulfGulp Grunt", hp = 55, damage = 10, speed = 10,
		color = Color3.fromRGB(50, 50, 60), accent = Color3.fromRGB(255, 180, 0),
		size = Vector3.new(2.6, 5.2, 2.2), telegraph = 0.5, attackCooldown = 1.5,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "LabBadge",
		flavor = "Corporate mascot energy.", shape = "humanoid", behavior = "chase" },
	{ id = "OilPuddleLayer", name = "Oil Puddle Layer", hp = 42, damage = 7, speed = 6,
		color = Color3.fromRGB(20, 25, 30), accent = Color3.fromRGB(80, 60, 20),
		size = Vector3.new(3, 2.5, 3), telegraph = 0.8, attackCooldown = 2.4,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "SpillAbsorbent",
		flavor = "Leaves slicks.", shape = "slime", behavior = "puddle" },
	{ id = "DroneSpotter", name = "GulfGulp Drone", hp = 30, damage = 6, speed = 12,
		color = Color3.fromRGB(60, 70, 90), accent = Color3.fromRGB(100, 255, 180),
		size = Vector3.new(2.5, 1.2, 2.5), telegraph = 0.4, attackCooldown = 1.6,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "LuckyPenny",
		flavor = "Hover-hop scanner.", shape = "drone", behavior = "hopper" },
	{ id = "MutantAdd", name = "Mutant Add", hp = 45, damage = 9, speed = 11,
		color = Color3.fromRGB(80, 200, 60), accent = Color3.fromRGB(255, 100, 0),
		size = Vector3.new(3, 3, 3), telegraph = 0.4, attackCooldown = 1.3,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = nil,
		flavor = "Anything is possible in the swamp.", shape = "lizard", behavior = "chase" },
	{ id = "SwampSummoner", name = "Swamp Summoner", hp = 60, damage = 8, speed = 5,
		color = Color3.fromRGB(70, 50, 90), accent = Color3.fromRGB(180, 100, 255),
		size = Vector3.new(3, 4.5, 3), telegraph = 1.0, attackCooldown = 3.0,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "HOACitation",
		flavor = "Calls cottonmouths.", shape = "humanoid", behavior = "summoner" },
	{ id = "PelicanBully", name = "Bully Pelican", hp = 44, damage = 9, speed = 10,
		color = Color3.fromRGB(240, 240, 230), accent = Color3.fromRGB(255, 160, 40),
		size = Vector3.new(3.5, 3.5, 3), telegraph = 0.45, attackCooldown = 1.5,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "FlipFlops",
		flavor = "Not Captain Steve. Rude.", shape = "pelican", behavior = "charger" },
	{ id = "RedTideBlob", name = "Red Tide Blob", hp = 55, damage = 10, speed = 5,
		color = Color3.fromRGB(180, 40, 60), accent = Color3.fromRGB(255, 80, 100),
		size = Vector3.new(4.5, 3, 4.5), telegraph = 0.7, attackCooldown = 2.0,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "TurtleSticker",
		flavor = "Bad for turtles.", shape = "slime", behavior = "puddle" },
	{ id = "LabCoat", name = "Rogue Lab Coat", hp = 48, damage = 9, speed = 11,
		color = Color3.fromRGB(230, 230, 240), accent = Color3.fromRGB(40, 180, 220),
		size = Vector3.new(2.4, 5, 2), telegraph = 0.5, attackCooldown = 1.4,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "LabBadge",
		flavor = "Science without ethics.", shape = "humanoid", behavior = "spitter" },
	{ id = "RigWelder", name = "Rig Welder", hp = 58, damage = 12, speed = 8,
		color = Color3.fromRGB(80, 80, 90), accent = Color3.fromRGB(255, 140, 40),
		size = Vector3.new(2.8, 5.2, 2.4), telegraph = 0.55, attackCooldown = 1.7,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "GatorSkinWallet",
		flavor = "Torch arcs.", shape = "humanoid", behavior = "firearc" },
	{ id = "BarrelRoller", name = "Barrel Roller", hp = 40, damage = 11, speed = 13,
		color = Color3.fromRGB(40, 50, 40), accent = Color3.fromRGB(255, 180, 0),
		size = Vector3.new(3, 3, 3), telegraph = 0.35, attackCooldown = 2.0,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = nil,
		flavor = "Hazardous freestyle.", shape = "barrel", behavior = "charger" },
	{ id = "MosquitoCloud", name = "Mosquito Cloud", hp = 22, damage = 4, speed = 14,
		color = Color3.fromRGB(40, 50, 40), accent = Color3.fromRGB(100, 120, 80),
		size = Vector3.new(4, 3, 4), telegraph = 0.3, attackCooldown = 0.9,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "ExpiredSunscreen",
		flavor = "Buzz. Bite. Repeat.", shape = "cloud", behavior = "hopper" },
	{ id = "CondoKaren", name = "Condo Karen", hp = 52, damage = 10, speed = 9,
		color = Color3.fromRGB(255, 180, 160), accent = Color3.fromRGB(200, 40, 80),
		size = Vector3.new(2.5, 5.1, 2.1), telegraph = 0.6, attackCooldown = 1.8,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "HOACitation",
		flavor = "Wants the manager of the swamp.", shape = "humanoid", behavior = "spitter" },
	{ id = "JetSkiBandit", name = "Jet Ski Bandit", hp = 46, damage = 11, speed = 17,
		color = Color3.fromRGB(40, 120, 200), accent = Color3.fromRGB(255, 80, 80),
		size = Vector3.new(4, 2.5, 2), telegraph = 0.4, attackCooldown = 1.5,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "FlipFlops",
		flavor = "Wake-jump charger.", shape = "cart", behavior = "charger" },
	{ id = "OffshoreCrab", name = "Offshore Crab", hp = 50, damage = 12, speed = 9,
		color = Color3.fromRGB(160, 40, 50), accent = Color3.fromRGB(255, 120, 60),
		size = Vector3.new(4, 2, 4), telegraph = 0.5, attackCooldown = 1.4,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "LiveBait",
		flavor = "Oil-stained claws.", shape = "crab", behavior = "scuttle" },
	{ id = "StormPelican", name = "Storm Pelican", hp = 90, damage = 10, speed = 12,
		color = Color3.fromRGB(200, 210, 220), accent = Color3.fromRGB(80, 120, 180),
		size = Vector3.new(4, 3.5, 3.5), telegraph = 0.5, attackCooldown = 1.4,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "LuckyPenny",
		flavor = "Wind hoppers.", shape = "pelican", behavior = "hopper" },
	{ id = "CrabKingBoss", name = "Crab King", hp = 120, damage = 11, speed = 9,
		color = Color3.fromRGB(180, 30, 40), accent = Color3.fromRGB(255, 220, 100),
		size = Vector3.new(5.5, 3, 5.5), telegraph = 0.6, attackCooldown = 1.5,
		isBoss = false, isMiniboss = true, isAlly = false, dropsPersona = "CrabKing", dropsItem = "LiveBait",
		flavor = "Sideways royalty.", shape = "crab", behavior = "scuttle" },
	{ id = "SlushieKing", name = "Slushie King", hp = 140, damage = 12, speed = 6,
		color = Color3.fromRGB(255, 40, 140), accent = Color3.fromRGB(80, 255, 255),
		size = Vector3.new(5, 5, 5), telegraph = 0.75, attackCooldown = 2.0,
		isBoss = false, isMiniboss = true, isAlly = false, dropsPersona = nil, dropsItem = "GasStationTaquito",
		flavor = "Sticky crown.", shape = "slime", behavior = "puddle" },
	{ id = "HOAHydra", name = "HOA Hydra", hp = 180, damage = 13, speed = 7,
		color = Color3.fromRGB(100, 60, 120), accent = Color3.fromRGB(255, 200, 80),
		size = Vector3.new(6, 5, 4), telegraph = 0.7, attackCooldown = 1.8,
		isBoss = false, isMiniboss = true, isAlly = false, dropsPersona = nil, dropsItem = "HOACitation",
		flavor = "Three clipboards. Zero chill.", shape = "boss", behavior = "summoner" },
	{ id = "RigOverlord", name = "Rig Overlord", hp = 220, damage = 15, speed = 6,
		color = Color3.fromRGB(30, 35, 45), accent = Color3.fromRGB(255, 160, 0),
		size = Vector3.new(8, 7, 5), telegraph = 0.8, attackCooldown = 2.0,
		isBoss = false, isMiniboss = true, isAlly = false, dropsPersona = nil, dropsItem = "LabBadge",
		flavor = "Middle management of doom.", shape = "boss", behavior = "firearc" },
	{ id = "Spillfather", name = "The Spillfather", hp = 520, damage = 18, speed = 7,
		color = Color3.fromRGB(20, 25, 30), accent = Color3.fromRGB(255, 140, 0),
		size = Vector3.new(12, 8, 6), telegraph = 0.85, attackCooldown = 2.2,
		isBoss = true, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "LabBadge",
		flavor = "CEO of sludge.", shape = "boss", behavior = "tank" },
	{ id = "RescueTurtle", name = "Baby Turtle", hp = 9999, damage = 0, speed = 4,
		color = Color3.fromRGB(80, 160, 100), accent = Color3.fromRGB(200, 255, 180),
		size = Vector3.new(2, 1.2, 2.4), telegraph = 0, attackCooldown = 99,
		isBoss = false, isMiniboss = false, isAlly = true, dropsPersona = "TurtlePaladin", dropsItem = "TurtleSticker",
		flavor = "Always an ally.", shape = "turtle", behavior = "chase" },
}

Enemies.List = list
Enemies.ById = {} :: { [string]: EnemyDef }
for _, e in list do
	Enemies.ById[e.id] = e
end

function Enemies.Get(id: string): EnemyDef?
	return Enemies.ById[id]
end

function Enemies.Count(): number
	return #list
end

return Enemies
