--!strict
--[[ Enemy catalog — Florida Man folklore headlines. Cartoon violence. Turtles always allies.
	Roles kept: charger, spitter, burrower, hopper, summoner, puddle, firearc, tank, boss, scuttle, chase.
]]

local Enemies = {}

export type EnemyDef = {
	id: string,
	name: string,
	hp: number,
	damage: number,
	speed: number,
	color: Color3,
	accent: Color3,
	size: Vector3,
	telegraph: number,
	attackCooldown: number,
	isBoss: boolean,
	isMiniboss: boolean,
	isAlly: boolean,
	dropsPersona: string?,
	dropsItem: string?,
	flavor: string,
	shape: string,
	behavior: string,
	telegraphColor: Color3?,
}

local list: { EnemyDef } = {
	-- Crabs / beach
	{ id = "BeachCrab", name = "Hangover Pincher", hp = 26, damage = 5, speed = 10,
		color = Color3.fromRGB(220, 70, 50), accent = Color3.fromRGB(255, 180, 100),
		size = Vector3.new(3.2, 1.6, 3.2), telegraph = 0.72, attackCooldown = 1.65,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = nil,
		flavor = "Stole your Cold One. Sideways and proud.", shape = "crab", behavior = "scuttle",
		telegraphColor = Color3.fromRGB(255, 120, 80) },
	{ id = "HermitCrab", name = "Stolen-Sunglasses Crab", hp = 38, damage = 7, speed = 7,
		color = Color3.fromRGB(180, 90, 60), accent = Color3.fromRGB(40, 40, 50),
		size = Vector3.new(2.8, 2.2, 2.8), telegraph = 0.55, attackCooldown = 1.7,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "SeashellShield",
		flavor = "Wears your shades. Shell tank. Slow pinch.", shape = "crab", behavior = "tank",
		telegraphColor = Color3.fromRGB(255, 200, 80) },
	{ id = "SandFlea", name = "Sand Flea", hp = 16, damage = 4, speed = 16,
		color = Color3.fromRGB(200, 180, 120), accent = Color3.fromRGB(255, 220, 160),
		size = Vector3.new(1.6, 1.2, 1.6), telegraph = 0.48, attackCooldown = 1.25,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = nil,
		flavor = "Annoying hoppers. Tutorial pests.", shape = "hopper", behavior = "hopper",
		telegraphColor = Color3.fromRGB(255, 240, 180) },
	{ id = "CrabKingBoss", name = "King of the Tide Pool", hp = 85, damage = 10, speed = 9,
		color = Color3.fromRGB(180, 30, 40), accent = Color3.fromRGB(255, 220, 100),
		size = Vector3.new(5.5, 3, 5.5), telegraph = 0.85, attackCooldown = 1.75,
		isBoss = false, isMiniboss = true, isAlly = false, dropsPersona = "CrabKing", dropsItem = "LiveBait",
		flavor = "Sideways royalty. Holds court over your Florida Dew.", shape = "crab", behavior = "scuttle",
		telegraphColor = Color3.fromRGB(255, 80, 60) },
	-- Tourists
	{ id = "AngryTourist", name = "Lost Tourist", hp = 36, damage = 7, speed = 9,
		color = Color3.fromRGB(255, 210, 160), accent = Color3.fromRGB(80, 140, 200),
		size = Vector3.new(2.4, 5, 2), telegraph = 0.68, attackCooldown = 1.8,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "IHeartFLShirt",
		flavor = "Lost. Taking it personally.", shape = "humanoid", behavior = "chase",
		telegraphColor = Color3.fromRGB(255, 160, 100) },
	{ id = "SelfieZombie", name = "Influencer Stick", hp = 32, damage = 6, speed = 8,
		color = Color3.fromRGB(255, 200, 180), accent = Color3.fromRGB(100, 200, 255),
		size = Vector3.new(2.2, 4.8, 2), telegraph = 0.75, attackCooldown = 2.1,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "CrackedVisor",
		flavor = "Selfie-stick flash stun telegraph, then shove.", shape = "humanoid", behavior = "spitter",
		telegraphColor = Color3.fromRGB(180, 240, 255) },
	{ id = "CondoKaren", name = "HOA Binder Karen", hp = 48, damage = 9, speed = 8,
		color = Color3.fromRGB(255, 180, 160), accent = Color3.fromRGB(200, 40, 80),
		size = Vector3.new(2.5, 5.1, 2.1), telegraph = 0.7, attackCooldown = 1.9,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "HOACitation",
		flavor = "Slow aura of paperwork. Wants the manager of the swamp.", shape = "humanoid", behavior = "spitter",
		telegraphColor = Color3.fromRGB(255, 80, 120) },
	{ id = "SlushieSlime", name = "Slushie Spill", hp = 32, damage = 6, speed = 7,
		color = Color3.fromRGB(255, 60, 160), accent = Color3.fromRGB(120, 255, 255),
		size = Vector3.new(3.5, 2.5, 3.5), telegraph = 0.72, attackCooldown = 2.0,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "GasStationTaquito",
		flavor = "Floor is sticky. Neon pink.", shape = "slime", behavior = "puddle",
		telegraphColor = Color3.fromRGB(255, 100, 200) },
	{ id = "HotDogCart", name = "Runaway Hotdog Cart", hp = 48, damage = 9, speed = 14,
		color = Color3.fromRGB(220, 40, 40), accent = Color3.fromRGB(255, 220, 80),
		size = Vector3.new(4, 3, 2.5), telegraph = 0.58, attackCooldown = 2.4,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "NoveltyMug",
		flavor = "Charger with mustard trail.", shape = "cart", behavior = "charger",
		telegraphColor = Color3.fromRGB(255, 200, 40) },
	{ id = "SlushieKing", name = "Slushie King", hp = 100, damage = 11, speed = 6,
		color = Color3.fromRGB(255, 40, 140), accent = Color3.fromRGB(80, 255, 255),
		size = Vector3.new(5, 5, 5), telegraph = 0.8, attackCooldown = 2.1,
		isBoss = false, isMiniboss = true, isAlly = false, dropsPersona = nil, dropsItem = "GasStationTaquito",
		flavor = "Sticky crown. Three phases of spill.", shape = "slime", behavior = "puddle",
		telegraphColor = Color3.fromRGB(255, 60, 180) },
	{ id = "HOAHydra", name = "HOA Hydra", hp = 125, damage = 12, speed = 7,
		color = Color3.fromRGB(100, 60, 120), accent = Color3.fromRGB(255, 200, 80),
		size = Vector3.new(6, 5, 4), telegraph = 0.75, attackCooldown = 1.9,
		isBoss = false, isMiniboss = true, isAlly = false, dropsPersona = nil, dropsItem = "HOACitation",
		flavor = "Three clipboards. Zero chill. Summons citations.", shape = "boss", behavior = "summoner",
		telegraphColor = Color3.fromRGB(200, 100, 255) },
	-- Gators / swamp
	{ id = "DriveThruGator", name = "Drive-Thru Gator", hp = 115, damage = 13, speed = 8,
		color = Color3.fromRGB(45, 110, 55), accent = Color3.fromRGB(255, 200, 40),
		size = Vector3.new(7, 3.2, 3.5), telegraph = 0.75, attackCooldown = 2.1,
		isBoss = false, isMiniboss = true, isAlly = false, dropsPersona = "GatorHauler", dropsItem = "RadioCollar",
		flavor = "Radio collar beeping. First real story beat.", shape = "gator", behavior = "tank",
		telegraphColor = Color3.fromRGB(255, 220, 60) },
	{ id = "Cottonmouth", name = "Rattle Cottonmouth", hp = 34, damage = 9, speed = 14,
		color = Color3.fromRGB(60, 80, 50), accent = Color3.fromRGB(240, 240, 220),
		size = Vector3.new(4, 1.2, 1.2), telegraph = 0.45, attackCooldown = 1.3,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = "SnakeCharmer", dropsItem = nil,
		flavor = "Warning rattle telegraph before the strike.", shape = "snake", behavior = "chase",
		telegraphColor = Color3.fromRGB(255, 255, 180) },
	{ id = "BurrowSnake", name = "Burrow Snake", hp = 36, damage = 9, speed = 11,
		color = Color3.fromRGB(80, 60, 40), accent = Color3.fromRGB(200, 180, 120),
		size = Vector3.new(3.5, 1.0, 1.0), telegraph = 0.6, attackCooldown = 1.9,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "LiveBait",
		flavor = "Pops from sand with a dirt ring telegraph.", shape = "snake", behavior = "burrower",
		telegraphColor = Color3.fromRGB(180, 140, 80) },
	{ id = "OilGator", name = "Collared Oil Gator", hp = 58, damage = 11, speed = 8,
		color = Color3.fromRGB(25, 35, 30), accent = Color3.fromRGB(255, 200, 40),
		size = Vector3.new(6, 2.8, 3), telegraph = 0.7, attackCooldown = 1.8,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "SpillAbsorbent",
		flavor = "Neon collar + sludge trail. GulfGulp property.", shape = "gator", behavior = "puddle",
		telegraphColor = Color3.fromRGB(255, 180, 40) },
	{ id = "FireLizard", name = "Fire-Breathing Lizard", hp = 46, damage = 11, speed = 12,
		color = Color3.fromRGB(255, 90, 20), accent = Color3.fromRGB(255, 220, 60),
		size = Vector3.new(3.5, 2.2, 4), telegraph = 0.55, attackCooldown = 1.6,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = "LizardBreath", dropsItem = nil,
		flavor = "Ground fire-cone telegraph. Cartoon burn.", shape = "lizard", behavior = "firearc",
		telegraphColor = Color3.fromRGB(255, 100, 20) },
	{ id = "EmberSkink", name = "Ember Skink", hp = 26, damage = 7, speed = 15,
		color = Color3.fromRGB(255, 140, 40), accent = Color3.fromRGB(255, 80, 20),
		size = Vector3.new(2.2, 1.4, 3), telegraph = 0.4, attackCooldown = 1.3,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "ExpiredSunscreen",
		flavor = "Tiny flame arcs on the ground.", shape = "lizard", behavior = "firearc",
		telegraphColor = Color3.fromRGB(255, 160, 40) },
	{ id = "MutantAdd", name = "Enhanced Specimen", hp = 44, damage = 9, speed = 11,
		color = Color3.fromRGB(80, 200, 60), accent = Color3.fromRGB(255, 100, 0),
		size = Vector3.new(3, 3, 3), telegraph = 0.45, attackCooldown = 1.4,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = nil,
		flavor = "Anything is possible in the swamp.", shape = "lizard", behavior = "chase",
		telegraphColor = Color3.fromRGB(120, 255, 80) },
	{ id = "SwampSummoner", name = "Swamp Open-Mic Host", hp = 58, damage = 8, speed = 5,
		color = Color3.fromRGB(70, 50, 90), accent = Color3.fromRGB(180, 100, 255),
		size = Vector3.new(3, 4.5, 3), telegraph = 1.05, attackCooldown = 3.1,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "HOACitation",
		flavor = "Calls cottonmouths. Purple circle telegraph.", shape = "humanoid", behavior = "summoner",
		telegraphColor = Color3.fromRGB(180, 80, 255) },
	{ id = "PelicanBully", name = "Bully Pelican", hp = 42, damage = 9, speed = 10,
		color = Color3.fromRGB(240, 240, 230), accent = Color3.fromRGB(255, 160, 40),
		size = Vector3.new(3.5, 3.5, 3), telegraph = 0.5, attackCooldown = 1.6,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "FlipFlops",
		flavor = "Not Captain Steve. Rude.", shape = "pelican", behavior = "charger",
		telegraphColor = Color3.fromRGB(255, 200, 120) },
	{ id = "MosquitoCloud", name = "Mosquito Cloud", hp = 20, damage = 4, speed = 14,
		color = Color3.fromRGB(40, 50, 40), accent = Color3.fromRGB(100, 120, 80),
		size = Vector3.new(4, 3, 4), telegraph = 0.35, attackCooldown = 1.0,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "ExpiredSunscreen",
		flavor = "Buzz. Bite. Repeat.", shape = "cloud", behavior = "hopper",
		telegraphColor = Color3.fromRGB(140, 160, 100) },
	{ id = "JetSkiBandit", name = "Jet Ski Bandit", hp = 44, damage = 10, speed = 17,
		color = Color3.fromRGB(40, 120, 200), accent = Color3.fromRGB(255, 80, 80),
		size = Vector3.new(4, 2.5, 2), telegraph = 0.45, attackCooldown = 1.6,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "FlipFlops",
		flavor = "Wake-jump charger.", shape = "cart", behavior = "charger",
		telegraphColor = Color3.fromRGB(80, 180, 255) },
	{ id = "OilPuddleLayer", name = "Oil Puddle Layer", hp = 40, damage = 7, speed = 6,
		color = Color3.fromRGB(20, 25, 30), accent = Color3.fromRGB(80, 60, 20),
		size = Vector3.new(3, 2.5, 3), telegraph = 0.85, attackCooldown = 2.5,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "SpillAbsorbent",
		flavor = "Leaves slicks that slow you.", shape = "slime", behavior = "puddle",
		telegraphColor = Color3.fromRGB(60, 50, 30) },
	-- Corp
	{ id = "GulfGulpGrunt", name = "Cheap Hazmat Grunt", hp = 46, damage = 10, speed = 10,
		color = Color3.fromRGB(50, 50, 60), accent = Color3.fromRGB(255, 180, 0),
		size = Vector3.new(2.6, 5.2, 2.2), telegraph = 0.55, attackCooldown = 1.6,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "LabBadge",
		flavor = "Corporate mascot energy. Yellow tape.", shape = "humanoid", behavior = "chase",
		telegraphColor = Color3.fromRGB(255, 200, 40) },
	{ id = "DroneSpotter", name = "Mark Drone", hp = 28, damage = 6, speed = 12,
		color = Color3.fromRGB(60, 70, 90), accent = Color3.fromRGB(100, 255, 180),
		size = Vector3.new(2.5, 1.2, 2.5), telegraph = 0.5, attackCooldown = 1.7,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "LuckyPenny",
		flavor = "Hover-hop. Marks you with a telegraph circle.", shape = "drone", behavior = "hopper",
		telegraphColor = Color3.fromRGB(100, 255, 180) },
	{ id = "LabCoat", name = "Sample Tosser", hp = 46, damage = 9, speed = 11,
		color = Color3.fromRGB(230, 230, 240), accent = Color3.fromRGB(40, 180, 220),
		size = Vector3.new(2.4, 5, 2), telegraph = 0.55, attackCooldown = 1.5,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "LabBadge",
		flavor = "Tosses 'samples.' Science without ethics.", shape = "humanoid", behavior = "spitter",
		telegraphColor = Color3.fromRGB(80, 220, 255) },
	{ id = "RigWelder", name = "Rig Welder", hp = 56, damage = 12, speed = 8,
		color = Color3.fromRGB(80, 80, 90), accent = Color3.fromRGB(255, 140, 40),
		size = Vector3.new(2.8, 5.2, 2.4), telegraph = 0.6, attackCooldown = 1.8,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "GatorSkinWallet",
		flavor = "Torch arcs on the ground.", shape = "humanoid", behavior = "firearc",
		telegraphColor = Color3.fromRGB(255, 140, 40) },
	{ id = "BarrelRoller", name = "Barrel Roller", hp = 38, damage = 11, speed = 13,
		color = Color3.fromRGB(40, 50, 40), accent = Color3.fromRGB(255, 180, 0),
		size = Vector3.new(3, 3, 3), telegraph = 0.4, attackCooldown = 2.1,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = nil,
		flavor = "Hazardous freestyle charger.", shape = "barrel", behavior = "charger",
		telegraphColor = Color3.fromRGB(255, 180, 0) },
	{ id = "RedTideBlob", name = "Red Tide Blob", hp = 52, damage = 10, speed = 5,
		color = Color3.fromRGB(180, 40, 60), accent = Color3.fromRGB(255, 80, 100),
		size = Vector3.new(4.5, 3, 4.5), telegraph = 0.75, attackCooldown = 2.1,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "TurtleSticker",
		flavor = "Bad for turtles. Cover for 'cleanup.'", shape = "slime", behavior = "puddle",
		telegraphColor = Color3.fromRGB(220, 40, 60) },
	{ id = "OffshoreCrab", name = "Offshore Pinch Crew", hp = 48, damage = 11, speed = 9,
		color = Color3.fromRGB(160, 40, 50), accent = Color3.fromRGB(255, 120, 60),
		size = Vector3.new(4, 2, 4), telegraph = 0.55, attackCooldown = 1.5,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "LiveBait",
		flavor = "Oil-stained claws. Clocked in late.", shape = "crab", behavior = "scuttle",
		telegraphColor = Color3.fromRGB(255, 100, 50) },
	{ id = "StormPelican", name = "Storm Pelican", hp = 85, damage = 10, speed = 12,
		color = Color3.fromRGB(200, 210, 220), accent = Color3.fromRGB(80, 120, 180),
		size = Vector3.new(4, 3.5, 3.5), telegraph = 0.55, attackCooldown = 1.5,
		isBoss = false, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "LuckyPenny",
		flavor = "Wind hoppers over the barge.", shape = "pelican", behavior = "hopper",
		telegraphColor = Color3.fromRGB(140, 180, 255) },
	{ id = "RigOverlord", name = "Rig Overlord", hp = 175, damage = 14, speed = 6,
		color = Color3.fromRGB(30, 35, 45), accent = Color3.fromRGB(255, 160, 0),
		size = Vector3.new(8, 7, 5), telegraph = 0.85, attackCooldown = 2.1,
		isBoss = false, isMiniboss = true, isAlly = false, dropsPersona = nil, dropsItem = "LabBadge",
		flavor = "Middle management of doom. Slam / summon / hazard.", shape = "boss", behavior = "firearc",
		telegraphColor = Color3.fromRGB(255, 140, 0) },
	{ id = "Spillfather", name = "The Spillfather", hp = 340, damage = 16, speed = 7,
		color = Color3.fromRGB(20, 25, 30), accent = Color3.fromRGB(255, 140, 0),
		size = Vector3.new(12, 8, 6), telegraph = 0.9, attackCooldown = 2.3,
		isBoss = true, isMiniboss = false, isAlly = false, dropsPersona = nil, dropsItem = "LabBadge",
		flavor = "Oil-exec sludge mech. Phases: slam, summon, arena slick.", shape = "boss", behavior = "tank",
		telegraphColor = Color3.fromRGB(255, 120, 0) },
	{ id = "RescueTurtle", name = "Baby Turtle", hp = 9999, damage = 0, speed = 4,
		color = Color3.fromRGB(80, 160, 100), accent = Color3.fromRGB(200, 255, 180),
		size = Vector3.new(2, 1.2, 2.4), telegraph = 0, attackCooldown = 99,
		isBoss = false, isMiniboss = false, isAlly = true, dropsPersona = "TurtlePaladin", dropsItem = "TurtleSticker",
		flavor = "Always an ally. Always.", shape = "turtle", behavior = "chase",
		telegraphColor = Color3.fromRGB(120, 255, 180) },
}

Enemies.List = list
Enemies.ById = {} :: { [string]: EnemyDef }
for _, e in list do
	Enemies.ById[e.id] = e
end

function Enemies.Get(id: string): EnemyDef?
	return Enemies.ById[id]
end

function Enemies.Count(): number
	return #list
end

return Enemies
